import { db } from "@/db";
import {
  businessProfiles,
  vehicles,
  availabilities,
  opportunities,
  scheduleEvents,
  incomeRecords,
  expenseRecords,
  mileageTrips,
  platformConnectors,
  selfHealingLogs,
  aiOpsMessages,
} from "@/db/schema";
import { sql } from "drizzle-orm";

export async function seedInitialDataIfNeeded() {
  const existingProfiles = await db.select().from(businessProfiles).limit(1);
  if (existingProfiles.length > 0) {
    return; // Already seeded
  }

  // 1. Business Profile
  await db.insert(businessProfiles).values({
    businessName: "Apex Direct Logistics LLC",
    legalStructure: "Single-Member LLC (Pass-Through)",
    stateOfRegistration: "California",
    einMasked: "XX-XXX8921",
    taxYear: 2026,
    targetDailyRevenue: "150.00",
    targetWeeklyRevenue: "950.00",
    targetMonthlyRevenue: "4200.00",
    taxReservePercent: "25.00",
    estMileageDeductionRate: "0.670",
    avgFuelCostPerGallon: "3.85",
    vehicleMpg: "28.5",
    xpPoints: 2450,
    level: 7,
    currentStreakDays: 6,
  });

  // 2. Primary Vehicle Telemetry
  await db.insert(vehicles).values([
    {
      name: "2023 Honda Civic EX-T (Courier Spec)",
      vinMasked: "1HGFC2F6...9942",
      licensePlate: "8KAP421",
      currentOdometer: "45328.4",
      startYearOdometer: "38100.0",
      status: "active",
      mpgRating: "29.4",
      oilLifePercent: 64,
      tireTreadPercent: 80,
      insuranceExpiration: "2026-11-20",
      isPrimary: true,
    },
    {
      name: "2019 Toyota Prius LE (Backup Fleet)",
      vinMasked: "JTDKN3DU...1108",
      licensePlate: "7XYZ309",
      currentOdometer: "89450.0",
      startYearOdometer: "87000.0",
      status: "active",
      mpgRating: "52.0",
      oilLifePercent: 88,
      tireTreadPercent: 90,
      insuranceExpiration: "2026-10-15",
      isPrimary: false,
    },
  ]);

  // 3. User Availability
  await db.insert(availabilities).values([
    { dayOfWeek: "Monday", startTime: "16:00", endTime: "22:00", isAvailable: true, maxHours: "6.0", notes: "Dinner peak focus" },
    { dayOfWeek: "Tuesday", startTime: "00:00", endTime: "00:00", isAvailable: false, maxHours: "0.0", notes: "Fleet maintenance & rest day" },
    { dayOfWeek: "Wednesday", startTime: "17:00", endTime: "22:00", isAvailable: true, maxHours: "5.0", notes: "Mid-week surge windows" },
    { dayOfWeek: "Thursday", startTime: "16:30", endTime: "22:30", isAvailable: true, maxHours: "6.0", notes: "Corporate catering & dinner" },
    { dayOfWeek: "Friday", startTime: "15:00", endTime: "23:00", isAvailable: true, maxHours: "8.0", notes: "High yield Friday sprint" },
    { dayOfWeek: "Saturday", startTime: "11:00", endTime: "22:00", isAvailable: true, maxHours: "9.0", notes: "Weekend prime window" },
    { dayOfWeek: "Sunday", startTime: "12:00", endTime: "20:00", isAvailable: true, maxHours: "7.0", notes: "Family brunch / dinner tail" },
  ]);

  // 4. Opportunities Pool
  const todayStr = new Date().toISOString().split("T")[0];
  await db.insert(opportunities).values([
    {
      platform: "DoorDash",
      opportunityType: "flexible_marketplace",
      title: "Westside Premium Dinner Surge",
      startTime: "17:30",
      endTime: "20:30",
      date: todayStr,
      expectedEarnings: "84.50",
      expectedMiles: "26.4",
      estimatedFuelCost: "3.56",
      estimatedNetProfit: "80.94",
      grossHourlyRate: "28.17",
      netHourlyRate: "26.98",
      score: 96,
      status: "available",
      source: "api_sync",
      zone: "Downtown / Westside Tech Corridor",
      recommendationReason: "🔥 High net rate ($26.98/hr), low fuel consumption, directly bridges your $150 daily target gap.",
    },
    {
      platform: "Uber Eats",
      opportunityType: "flexible_marketplace",
      title: "Metro Dinner Multi-Boost Boosted Zone",
      startTime: "18:00",
      endTime: "21:00",
      date: todayStr,
      expectedEarnings: "72.00",
      expectedMiles: "29.8",
      estimatedFuelCost: "4.02",
      estimatedNetProfit: "67.98",
      grossHourlyRate: "24.00",
      netHourlyRate: "22.66",
      score: 84,
      status: "available",
      source: "api_sync",
      zone: "Central Metro & University Heights",
      recommendationReason: "Good secondary backup. 1.4x boost multiplier active during 6:30-8:00 PM.",
    },
    {
      platform: "Crew",
      opportunityType: "fixed_commitment",
      title: "Scheduled Express Hub Dispatch Shift",
      startTime: "13:00",
      endTime: "16:30",
      date: todayStr,
      expectedEarnings: "68.25",
      expectedMiles: "15.0",
      estimatedFuelCost: "2.02",
      estimatedNetProfit: "66.23",
      grossHourlyRate: "19.50",
      netHourlyRate: "18.92",
      score: 91,
      status: "scheduled",
      source: "csv_import",
      zone: "Southport Logistics Park",
      recommendationReason: "🛡️ Guaranteed fixed hourly pay ($19.50/hr). Immune to slow marketplace fluctuations.",
    },
    {
      platform: "Amazon Flex",
      opportunityType: "scheduled_block",
      title: "Sub-Same-Day Prime Block (3.5hr)",
      startTime: "06:00",
      endTime: "09:30",
      date: todayStr,
      expectedEarnings: "87.50",
      expectedMiles: "42.0",
      estimatedFuelCost: "5.67",
      estimatedNetProfit: "81.83",
      grossHourlyRate: "25.00",
      netHourlyRate: "23.38",
      score: 79,
      status: "available",
      source: "manual_entry",
      zone: "Regional Delivery Hub DSD4",
      recommendationReason: "High payout block, higher mileage requirement (42 miles). Recommend for fuel-efficient Prius.",
    },
  ]);

  // 5. Schedule Events
  await db.insert(scheduleEvents).values([
    {
      title: "Crew - Scheduled Hub Dispatch",
      platform: "Crew",
      eventType: "fixed_commitment",
      date: todayStr,
      startTime: "13:00",
      endTime: "16:30",
      status: "completed",
      projectedEarnings: "68.25",
      projectedMiles: "15.0",
      actualEarnings: "68.25",
      actualMiles: "16.2",
      notes: "Completed smoothly. 11 parcels routed.",
    },
    {
      title: "DoorDash - Westside Dinner Wave",
      platform: "DoorDash",
      eventType: "flexible_gig",
      date: todayStr,
      startTime: "17:30",
      endTime: "20:30",
      status: "confirmed",
      projectedEarnings: "84.50",
      projectedMiles: "26.4",
      notes: "Selected shift to close remaining daily goal gap.",
    },
    {
      title: "Business Admin & Receipt Auditing",
      platform: "HQ Admin",
      eventType: "admin_audit",
      date: todayStr,
      startTime: "21:00",
      endTime: "21:30",
      status: "confirmed",
      projectedEarnings: "0.00",
      projectedMiles: "0.0",
      notes: "Weekly bookkeeping reconciliation & mileage ledger lock.",
    },
  ]);

  // 6. Income Records
  await db.insert(incomeRecords).values([
    {
      platform: "Crew",
      date: todayStr,
      timePeriod: "Afternoon Commitment",
      grossAmount: "68.25",
      tipsAmount: "0.00",
      platformFees: "0.00",
      netPayout: "68.25",
      milesDriven: "16.2",
      hoursWorked: "3.50",
      status: "verified",
      sourceReference: "CRW-202604-998",
      sourceType: "direct_connector",
    },
    {
      platform: "Uber Eats",
      date: todayStr,
      timePeriod: "Late Lunch Surge",
      grossAmount: "19.17",
      tipsAmount: "6.50",
      platformFees: "0.00",
      netPayout: "19.17",
      milesDriven: "8.5",
      hoursWorked: "0.70",
      status: "verified",
      sourceReference: "UBR-904123-US",
      sourceType: "direct_connector",
    },
    {
      platform: "DoorDash",
      date: "2026-04-17",
      timePeriod: "Dinner Dash Rush",
      grossAmount: "142.80",
      tipsAmount: "48.20",
      platformFees: "0.00",
      netPayout: "142.80",
      milesDriven: "54.2",
      hoursWorked: "5.50",
      status: "verified",
      sourceReference: "DD-992144-P",
      sourceType: "csv_import",
    },
    {
      platform: "Crew",
      date: "2026-04-16",
      timePeriod: "Morning Logistics Shift",
      grossAmount: "78.00",
      tipsAmount: "0.00",
      platformFees: "0.00",
      netPayout: "78.00",
      milesDriven: "18.0",
      hoursWorked: "4.00",
      status: "verified",
      sourceReference: "CRW-202604-912",
      sourceType: "direct_connector",
    },
    {
      platform: "DoorDash",
      date: "2026-04-15",
      timePeriod: "Dinner Shift",
      grossAmount: "118.50",
      tipsAmount: "39.00",
      platformFees: "0.00",
      netPayout: "118.50",
      milesDriven: "46.0",
      hoursWorked: "4.80",
      status: "verified",
      sourceReference: "DD-984421-P",
      sourceType: "direct_connector",
    },
  ]);

  // 7. Expense Records
  await db.insert(expenseRecords).values([
    {
      date: todayStr,
      merchant: "Chevron Station #0821",
      amount: "42.17",
      category: "fuel",
      paymentMethod: "Business Visa *4912",
      businessPurpose: "Fuel fill-up for commercial delivery shifts (Honda Civic)",
      businessUsePercent: "100.00",
      deductiblePortion: "42.17",
      receiptUrl: "https://images.unsplash.com/photo-1545459720-aac8509eb02c?auto=format&fit=crop&w=600&q=80",
      receiptOcrRaw: "CHEVRON #0821\n10.953 GAL REGULAR @ $3.850/G\nSUBTOTAL: $42.17\nVISA ENDING IN 4912\nOCT 18 2026",
      confidenceLevel: "high",
      status: "approved",
      notes: "AI categorized automatically; 100% business allocation.",
    },
    {
      date: "2026-04-16",
      merchant: "Jiffy Lube Express Care",
      amount: "89.99",
      category: "vehicle_maintenance",
      paymentMethod: "Business Visa *4912",
      businessPurpose: "Full Synthetic Oil Change & Filter Replacement (45,000 mi service)",
      businessUsePercent: "85.00",
      deductiblePortion: "76.49",
      receiptUrl: "https://images.unsplash.com/photo-1486006920555-c77dce18193b?auto=format&fit=crop&w=600&q=80",
      confidenceLevel: "high",
      status: "approved",
      notes: "Mileage-based maintenance schedule trigger.",
    },
    {
      date: "2026-04-14",
      merchant: "T-Mobile USA Business",
      amount: "75.00",
      category: "phone_internet",
      paymentMethod: "Business Auto-Debit *4912",
      businessPurpose: "Primary dispatch & GPS data line for courier operation",
      businessUsePercent: "80.00",
      deductiblePortion: "60.00",
      confidenceLevel: "high",
      status: "approved",
      notes: "Monthly business cellular allocation.",
    },
    {
      date: "2026-04-10",
      merchant: "AutoZone Parts #332",
      amount: "28.50",
      category: "supplies",
      paymentMethod: "Business Visa *4912",
      businessPurpose: "Heavy-duty commercial insulated catering food bag & sanitizer",
      businessUsePercent: "100.00",
      deductiblePortion: "28.50",
      confidenceLevel: "high",
      status: "approved",
      notes: "Required equipment for hot food delivery compliance.",
    },
  ]);

  // 8. Mileage Trips
  await db.insert(mileageTrips).values([
    {
      date: todayStr,
      platform: "Crew",
      startOdometer: "45303.7",
      endOdometer: "45319.9",
      businessMiles: "16.2",
      personalMiles: "0.0",
      purpose: "Crew Hub Dispatch Route #14",
      startLocation: "Southport Logistics Park",
      endLocation: "Midtown Commercial Core",
      standardDeductionValue: "10.85", // 16.2 * $0.67
      loggedVia: "telemetry_auto",
    },
    {
      date: todayStr,
      platform: "Uber Eats",
      startOdometer: "45319.9",
      endOdometer: "45328.4",
      businessMiles: "8.5",
      personalMiles: "0.0",
      purpose: "Uber Eats Afternoon Surge Orders",
      startLocation: "Midtown Core",
      endLocation: "Westside Hub",
      standardDeductionValue: "5.70",
      loggedVia: "telemetry_auto",
    },
    {
      date: "2026-04-17",
      platform: "DoorDash",
      startOdometer: "45249.5",
      endOdometer: "45303.7",
      businessMiles: "54.2",
      personalMiles: "2.1",
      purpose: "DoorDash Dinner Shift",
      startLocation: "HQ Hub",
      endLocation: "Downtown Metro Corridor",
      standardDeductionValue: "36.31",
      loggedVia: "telemetry_auto",
    },
  ]);

  // 9. Platform Connectors
  await db.insert(platformConnectors).values([
    {
      connectorKey: "doordash",
      name: "DoorDash Official Driver API / CSV Bridge",
      connectorType: "approved_api",
      status: "healthy",
      lastSyncAt: new Date(Date.now() - 15 * 60 * 1000),
      syncItemCount: 142,
      authExpiry: "2026-09-30",
      diagnostics: { latencyMs: 240, activeWebhook: true, syncMode: "OAuth + Nightly CSV Reconcile" },
    },
    {
      connectorKey: "uber_eats",
      name: "Uber Eats Direct Driver Data Connector",
      connectorType: "approved_api",
      status: "healthy",
      lastSyncAt: new Date(Date.now() - 18 * 60 * 1000),
      syncItemCount: 98,
      authExpiry: "2026-11-15",
      diagnostics: { latencyMs: 310, activeWebhook: true, syncMode: "OAuth Direct Stream" },
    },
    {
      connectorKey: "crew",
      name: "Crew Enterprise Scheduling & Roster Feed",
      connectorType: "webhook_feed",
      status: "healthy",
      lastSyncAt: new Date(Date.now() - 42 * 60 * 1000),
      syncItemCount: 34,
      authExpiry: "Permanent Token",
      diagnostics: { latencyMs: 180, activeWebhook: true, commitmentMode: "Fixed Schedule Enforced" },
    },
    {
      connectorKey: "bank_feed",
      name: "Plaid Business Banking Feed (*4912)",
      connectorType: "approved_api",
      status: "healthy",
      lastSyncAt: new Date(Date.now() - 35 * 60 * 1000),
      syncItemCount: 88,
      authExpiry: "2026-12-31",
      diagnostics: { latencyMs: 140, institution: "Chase Commercial Banking" },
    },
    {
      connectorKey: "receipt_ocr",
      name: "Tesseract OCR & Document AI Engine",
      connectorType: "local_ocr",
      status: "healthy",
      lastSyncAt: new Date(Date.now() - 10 * 60 * 1000),
      syncItemCount: 29,
      diagnostics: { avgConfidence: "98.2%", autoCategorizationRate: "94%" },
    },
    {
      connectorKey: "mileage_telemetry",
      name: "OBD-II & GPS Telemetry Sync",
      connectorType: "webhook_feed",
      status: "healthy",
      lastSyncAt: new Date(Date.now() - 5 * 60 * 1000),
      syncItemCount: 412,
      diagnostics: { accuracyRadius: "3m", protocol: "Bouncie/Automatic Bridge" },
    },
  ]);

  // 10. Self-Healing Logs
  await db.insert(selfHealingLogs).values([
    {
      incidentCode: "TARGET_GAP_DETECTED",
      stage: "repaired",
      summary: "Daily Target Gap of $62.58 identified after afternoon shift",
      details: "User completed Crew shift earning $68.25 + Uber lunch ($19.17) = $87.42 gross. Daily target is $150.00. Remaining deficit: $62.58.",
      actionTaken: "Ranked open marketplace opportunities. Identified DoorDash 17:30-20:30 shift ($84.50 expected) as optimal bridge. Shift pre-staged for one-click confirmation.",
      impactAmount: "84.50",
      userNotified: true,
      requiresUserConfirmation: false,
      confirmedByUser: true,
    },
    {
      incidentCode: "SHIFT_DROPPED",
      stage: "repaired",
      summary: "Crew secondary shift cancelled by warehouse dispatcher",
      details: "Crew dispatcher cancelled 19:00-21:00 auxiliary block due to container delay at port terminal.",
      actionTaken: "Detected webhook cancellation -> Cleared block from calendar -> Unlocked evening availability -> Auto-suggested Westside DoorDash peak surge.",
      impactAmount: "45.00",
      userNotified: true,
      requiresUserConfirmation: true,
      confirmedByUser: true,
    },
    {
      incidentCode: "DUPLICATE_TX_FLAGGED",
      stage: "repaired",
      summary: "Prevented duplicate income record on Uber Eats payout statement",
      details: "Import statement contained order #88412 already recognized through realtime webhook.",
      actionTaken: "Deduplication hash check matched -> Skipped duplicate import row -> Audit log preserved.",
      impactAmount: "14.20",
      userNotified: true,
      requiresUserConfirmation: false,
      confirmedByUser: true,
    },
  ]);

  // 11. Initial AI Ops Manager Messages
  await db.insert(aiOpsMessages).values([
    {
      sender: "nova",
      message: "🚀 Mission Control initialized. Good afternoon! Today you have booked $87.42 across Crew and Uber Eats. Your daily target is $150.00 (progress: 58%). DoorDash Westside Dinner (5:30 PM - 8:30 PM) is your highest-yielding bridge to crush the goal today.",
      contextCard: {
        type: "shift_recommendation",
        platform: "DoorDash",
        time: "5:30 PM - 8:30 PM",
        expectedEarnings: "$84.50",
        expectedProfit: "$80.94",
        reasons: ["28.17/hr gross rate", "26.4 planned miles", "Closes daily goal to 114%"],
      },
    },
  ]);
}